### ISSUE TITLE
Update to use middleware.json

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-example-passport#39]
It would be good to see how this should be implemented using the new middleware.json syntax.

**Comment by crandmck** [comment]
The app has https://github.com/strongloop/loopback-example-passport/blob/master/server/middleware.json.   What more are you after?

**Comment by gausie** [comment]
That's just the template middleware.json. I'll paste an example of what I
use when I can.

**Comment by sanori** [comment]
I have a similar issue.
In this example, all the middleware and route settings are in `server.js` and `boot/*.js`. It would be best if most of the `app.middleware()` and `app.use()` calls are moved to `middleware.json`.

For example, in strongloop@5.0.1 template, `middleware.json` sets the route to `${restApiRoot}` as follows.
```json
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  }
```

**Comment by superkhau** [comment]
@gausie @sanori Would you guys like to submit a patch?

@crandmck Do the docs have sufficient info on `middleware.json` for @gausie or @sanori to submit a patch themselves?

**Comment by crandmck** [comment]
@superkhau I believe so-- [Defining middleware](https://docs.strongloop.com/display/LB/Defining+middleware) should explain things sufficiently.

Also, the changes are covered by https://github.com/strongloop-internal/scrum-loopback/issues/495, but since that's an internal repo, I've reproduced the instructions below.  Note that these instructions are also for upgrading to the new Explorer.

@gausie @sanori Let me know if you need more info.
---
Since `loopback-explorer` was renamed to `loopback-component-explorer` (see https://github.com/strongloop/loopback-component-explorer/issues/123), we need to propagate this change to the example apps; specifically the same changes made in https://github.com/strongloop/loopback-example-app/pull/79:

**1.** In `package.json`, change 

` "loopback-explorer": "^2.0.0",` to  `"loopback-component-explorer": "^2.1.0",`

**2.** In `server/component-config.json`, change 
```
{
  "loopback-explorer": {
     "mountPath": "/explorer"
   }
 }
```
to 
```
{
  "loopback-component-explorer": {
     "mountPath": "/explorer"
   }
 }
```

NOTE: Many examples will not have  `server/component-config.json`, so in that case just add the file.

**3.** In `server/server.js`, change

```
if (app.get('loopback-explorer')) {
      var explorerPath = app.get('loopback-explorer').mountPath;
```
to 
```
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
```
 **4.** Remove `server/boot/explorer.js` since it's now done in `component-config.json`.

As long as we're doing, this we might as well also remove `server/boot/rest-api.js` and add the following line to `middleware.json`: 
```
"routes": {
    "loopback#rest": {
      "paths": ["${restApiRoot}"]
    },
...
```
